name: Replica Set Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  replica-set-on-default-port:
    name: MongoDB v${{ matrix.mongodb-version }} RS — Node.js v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        mongodb-version: ['4.0', '4.2', '4.4', '5.0', '6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs
          mongodb-replica-set-node-ports: "27017,27117,27217"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/replica-set
        env:
          CI: true
          MONGODB_REPLICA_SET: mongodb-test-rs
          MONGODB_PORTS: "27017,27117,27217"

  replica-set-on-custom-port:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        mongodb-port: [23456]
        mongodb-version: ['4.0', '4.2', '4.4']

    name: MongoDB v${{ matrix.mongodb-version }} RS, Port ${{ matrix.mongodb-port }} — Node.js v${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-port: ${{ matrix.mongodb-port }}
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs
          mongodb-replica-set-node-ports: "27017,27117,27217"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/replica-set
        env:
          CI: true
          MONGODB_PORT: ${{ matrix.mongodb-port }}
          MONGODB_PORTS: "27017,27117,27217"
          MONGODB_REPLICA_SET: mongodb-test-rs
